# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b9bcb15d248bd05f368e6ced9be9c69eddf0372246ec3029a2864d8984b1698cd06d894dcb9e96b13b35d82a887bfd307b0fbdc548b6894028faa1d6270a878

test:
  secret_key_base: d460e1f53ca15cff863c30bf732e7e9747f8782e06067c8393de3f00c1ad0ecb798f28920a3827b8de8efc5105687bf331417b5efd5db1dc031912e26daf03ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
